{
  "name": "b75958ca-a0af-4664-bc44-4bc3e81721cc",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "tables": [
      {
        "name": "Sales",
        "lineageTag": "d3e7f3c9-5bed-4c10-84ad-cba219117c46",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "unused",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[unused]",
            "lineageTag": "5d192bfd-3c9a-4a96-8cb3-e92cc1e5f181",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sales-13ba55b2-f562-4358-bbe2-1e5e6c4ad6d6",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "DATATABLE(\"unused\", STRING, {{}})"
            }
          }
        ],
        "measures": [
          {
            "name": "Hello World",
            "expression": "0",
            "formatString": "0",
            "displayFolder": "Finacial",
            "lineageTag": "265a4bd3-48a0-4d64-af07-30b6bfc1a14a"
          },
          {
            "name": "Sales Revenue",
            "expression": "0",
            "formatString": "0",
            "displayFolder": "Finacial",
            "lineageTag": "364450f0-28a6-4966-9f08-20ab940975cd"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f74b62feaf9a481581ad1bb58922cf4c"
          }
        ]
      },
      {
        "name": "Translated Dataset Object Labels",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "unsed",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[unsed]",
            "displayFolder": "unused"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "source": {
              "type": "calculated",
              "expression": "DATATABLE(\"unsed\", STRING, {{\"This is a table automatically generated by TranslationBuilder\"}})"
            }
          }
        ],
        "measures": [
          {
            "name": "Sales",
            "expression": "SWITCH(LEFT(USERCULTURE(), 2),\n   \"es\", \"Ventas\",\n   \"Sales\"\n)"
          },
          {
            "name": "Sales:Hello World",
            "expression": "SWITCH(LEFT(USERCULTURE(), 2),\n   \"es\", \"Hola Mundo\",\n   \"Hello World\"\n)"
          },
          {
            "name": "Sales:Sales Revenue",
            "expression": "SWITCH(LEFT(USERCULTURE(), 2),\n   \"es\", \"Ingresos Por Ventas\",\n   \"Sales Revenue\"\n)"
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {},
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Sales",
                "translatedCaption": "Sales",
                "measures": [
                  {
                    "name": "Hello World",
                    "translatedCaption": "Hello World",
                    "translatedDisplayFolder": "Finacial"
                  },
                  {
                    "name": "Sales Revenue",
                    "translatedCaption": "Sales Revenue",
                    "translatedDisplayFolder": "Finacial"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "es-ES",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Sales",
                "translatedCaption": "Ventas",
                "measures": [
                  {
                    "name": "Hello World",
                    "translatedCaption": "Hola Mundo",
                    "translatedDisplayFolder": "Financiero"
                  },
                  {
                    "name": "Sales Revenue",
                    "translatedCaption": "Ingresos Por Ventas",
                    "translatedDisplayFolder": "Financiero"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.110.1161.0 (22.10)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ]
  }
}